### ISSUE TITLE
Incorrect district id for city "Akurana"

### ISSUE THREAD

**Issue by nmmanas** [madurapa/sri-lanka-provinces-districts-cities#17]
https://github.com/madurapa/sri-lanka-provinces-districts-cities/blob/2a31a14309c9d5fd8d3d739cd04011b7b5f86840/cities.sql#L1061

the above record "Akurana" city is part of Kandy district, hence the district code should be 2.

**Comment by jayasanka-sack** [comment]
@madurapa I'm working with a new PR. Please do not fix this until I open it.

**Comment by jayasanka-sack** [comment]
@nmmanas  Thank you for the contribution! :smiley: 
Actually the correct ID for the Kandy district is 11

**Comment by madurapa** [comment]
@nmmanas  this issue is fixed by @jayasanka-sack 
Thanks, guys
