### ISSUE TITLE
Incomplete city table

### ISSUE THREAD

**Issue by nishantha-kumara** [madurapa/sri-lanka-provinces-districts-cities#27]
City table is incomplete. Please check

**Comment by madurapa** [comment]
Can you please tell me what cities are missing?

**Comment by nishantha-kumara** [comment]
Hi, @madurapa I don't know which city is missing. but your city SQL table has some SQL issues.

**Comment by madurapa** [comment]
The issue has been fixed. Thank you very much for your support!
