### ISSUE TITLE
Translation Effort For Sinhala And Tamil

### ISSUE THREAD

**Issue by kaveenr** [madurapa/sri-lanka-provinces-districts-cities#45]
Hey all, 

We've been working on a project for some time, building a memorial for those who lost their lives to COVID-19.
As the site is localized to all 3 languages, we have translated some city data to Sinhala & Tamil.  **Currently, we're just translating whatever cities we have used in our project.**

I initially dump'd the data of your great project into JSON from MySQL as that was easy for me to handle.
The translation is done over [Google Sheets](https://docs.google.com/spreadsheets/d/1fQtlao4rZiyLGJJcmSjopmaWdKihEsBwI2_bRJQCSkk/edit#gid=909471990) and dumped automatically to this [JSON](https://raw.githubusercontent.com/kaveenr/covid19-memorial-lk-data/data/data/geo_processed_latest.json) file.

I'd love for these changes to hit upstream as well. Thanks!

**Comment by kaveenr** [comment]
Might I suggest, that the data be stored in JSON/YAML. Then use a script to generator the migration scripts?
This will allow, a lot more folks to use the dataset and also allow easy editing as well.

**Comment by madurapa** [comment]
Thank you very much, bro!
I have updated some of the Tamil translations as per the Google Sheet.
