### ISSUE TITLE
Hanguranketha does not belong to Kandy.

### ISSUE THREAD

**Issue by dhanushka3** [madurapa/sri-lanka-provinces-districts-cities#49]
Hanguranketa town and Marymount colony do not belong to the Kandy district. Update them as towns in the Nuwara-Eliya District.
reference:
https://en.wikipedia.org/wiki/Hanguranketha
http://www.dinamina.lk/2017/07/05/%E0%B6%B4%E0%B7%8A%E2%80%8D%E0%B6%BB%E0%B7%8F%E0%B6%AF%E0%B7%9A%E0%B7%81%E0%B7%93%E0%B6%BA/36842?page=7

The name Gunnepana should be changed to "ගුන්නෑපාන" when writing in Sinhala.
The name Kolabissa should be changed to "කොළඹිස්ස" when writing in Sinhala.
The name Rantebe should be changed to "රන්ටැඹේ" when writing in Sinhala.

**Comment by madurapa** [comment]
Thanks, fixed the issues.

**Comment by dhanushka3** [comment]
you are welcome and thanks.
